apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-configmap
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "todo-app.commonLabels" . | nindent 4 }}
data:
  JWT_ISSUER: {{ .Values.api.config.jwtIssuer | quote }}
  JWT_AUDIENCE: {{ .Values.api.config.jwtAudience | quote }}
  RUN_MIGRATIONS: {{ .Values.api.config.runMigrations | quote }}
  ENABLE_SWAGGER: {{ .Values.api.config.enableSwagger | quote }}
