apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "todo-app.commonLabels" . | nindent 4 }}
    {{- include "todo-app.apiSelectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-app.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-app.commonLabels" . | nindent 8 }}
        {{- include "todo-app.apiSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
              name: api
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: mysql-root-password
            - name: DB_CONNECTION_STRING
              value: Server={{ .Values.db.config.host }};Port={{ .Values.db.port }};Database={{ .Values.db.config.databaseName }};User={{ .Values.db.config.user }};Password=$(DB_PASSWORD);
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: jwt-secret
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: JWT_ISSUER
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: JWT_AUDIENCE
            - name: RUN_MIGRATIONS
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: RUN_MIGRATIONS
            - name: ENABLE_SWAGGER
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: ENABLE_SWAGGER
          {{- if .Values.api.resources }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- end }}
