apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "todo-app.commonLabels" . | nindent 4 }}
    {{- include "todo-app.uiSelectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-app.uiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-app.commonLabels" . | nindent 8 }}
        {{- include "todo-app.uiSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ui.port }}
              name: http
          {{- if .Values.ui.resources }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          {{- end }}
