apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "todo-app.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
