apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "todo-app.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.db.rootPassword | quote }}
  jwt-secret: {{ .Values.jwt.secret | quote }}
