apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "todo-app.commonLabels" . | nindent 4 }}
    {{- include "todo-app.uiSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.uiSelectorLabels" . | nindent 4 }}
