apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "todo-app.commonLabels" . | nindent 4 }}
    {{- include "todo-app.dbSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      protocol: TCP
      name: mysql
  selector:
    {{- include "todo-app.dbSelectorLabels" . | nindent 4 }}
