{{- define "todo-mysql-secret-callback" -}}
{{- $root := .root -}}
mysql-root-password: {{ $root.Values.components.db.rootPassword | quote }}
jwt-secret: {{ $root.Values.jwt.secret | quote }}
{{- end -}}
